# Generated by Django 5.0.6 on 2024-06-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='class_groups',
            field=models.ManyToManyField(blank=True, to='admissions.classgroup'),
        ),
    ]
